// Effects index — re-exports all effect configs and resolvers.
export { WEIGHT_META, WEIGHT_VALUES, resolveWeight, type WeightEffect } from './weight/weight-config'
export { weightResolver } from './weight/weight-resolver'
export { HEADS_META, HEADS_VALUES, resolveHeads, type HeadsEffect } from './heads/heads-config'
export { headsResolver } from './heads/heads-resolver'
export { TAILS_META, TAILS_VALUES, resolveTails, type TailsEffect } from './tails/tails-config'
export { tailsResolver } from './tails/tails-resolver'
export { FACEDOWN_META, FACEDOWN_VALUES, resolveFacedown, type FacedownEffect } from './facedown/facedown-config'
export { facedownResolver } from './facedown/facedown-resolver'
export { CHAOS_META, CHAOS_VALUES, resolveChaos, type ChaosEffect } from './chaos/chaos-config'
export { chaosResolver } from './chaos/chaos-resolver'
export { ECHO_META, ECHO_VALUES, resolveEcho, type EchoEffect } from './echo/echo-config'
export { echoResolver } from './echo/echo-resolver'
export { MAGNETIC_META, MAGNETIC_VALUES, resolveMagnetic, type MagneticEffect } from './magnetic/magnetic-config'
export { magneticResolver } from './magnetic/magnetic-resolver'
export { REVERSE_META, REVERSE_VALUES, resolveReverse, type ReverseEffect } from './reverse/reverse-config'
export { reverseResolver } from './reverse/reverse-resolver'
export { TAX_META, TAX_VALUES, resolveTax, type TaxEffect } from './tax/tax-config'
export { taxResolver } from './tax/tax-resolver'
export { JACKPOT_META, JACKPOT_VALUES, resolveJackpot, type JackpotEffect } from './jackpot/jackpot-config'
export { jackpotResolver } from './jackpot/jackpot-resolver'
export { DRAW_META, DRAW_VALUES, resolveDraw, type DrawEffect } from './draw/draw-config'
export { drawResolver } from './draw/draw-resolver'
