// Coin module — public API.
export { Coin } from './coin'
export type { CoinProps } from './coin'
export { CoinShell } from './coin-shell'
export { CoinGlyph } from './coin-glyph'
export { CoinMotion } from './coin-motion'
export { resolveCoinFace, resolveCoinFaces, highestPriorityEffect } from './coin-resolver'
export { fireCoinEvent } from './coin-events'
export type { CoinEventHooks, CoinEventType, CoinEventPayload, CoinEventHandler } from './coin-events'
export type { CoinVisualModifier, ResolvedCoinFace, ResolverInput } from './coin-types'
