// SFX (13.7) — the sound map from SDD UX §10, played through Howler.
//
// 16 events (UX §10 table): deal, pick, unpick, discard, toss, land,
// tierHit, chip, mult, cash, button, reroll, buy, error, winStinger,
// loseStinger. Assets are synthesized CC0 .wav files in
// public/resource/sfx (generated by scripts/generate-sfx.mjs).
//
// Design (UX §9/§10):
//  - **Lazy**: the Howl objects are created on the first play (which always
//    follows a user gesture — the first draw is a button press), so no audio
//    work happens at load.
//  - **Concurrency cap**: at most MAX_CONCURRENT simultaneous voices; extra
//    plays are dropped (fast chip ticks never pile up).
//  - **Ducking**: a big event (tier hit, stingers) ducks the small ones for
//    DUCK_MS so the escalation reads in audio too.
//  - **Rate**: the toss/land ±5% and the rising chip ticks come in as
//    `rate` options from the call sites.
//
// Purely presentational (UX §0): sfx never gate an action, and a missing
// asset or a blocked AudioContext just means silence — never an error.

import { Howl } from 'howler'

/** The 16 sound-map events (UX §10). */
export type SfxEvent =
  | 'deal'
  | 'pick'
  | 'unpick'
  | 'discard'
  | 'toss'
  | 'land'
  | 'tierHit'
  | 'chip'
  | 'mult'
  | 'cash'
  | 'button'
  | 'reroll'
  | 'buy'
  | 'error'
  | 'winStinger'
  | 'loseStinger'

/** Base volume per event (UX §10): small events quiet, tier hits and the
 *  blind-clear stinger loud. */
const VOLUME: Record<SfxEvent, number> = {
  deal: 0.35,
  pick: 0.3,
  unpick: 0.3,
  discard: 0.35,
  toss: 0.4,
  land: 0.45,
  tierHit: 0.8,
  chip: 0.3,
  mult: 0.6,
  cash: 0.5,
  button: 0.25,
  reroll: 0.35,
  buy: 0.4,
  error: 0.4,
  winStinger: 0.9,
  loseStinger: 0.8,
}

/** The "big" events that duck everything else (UX §10). */
const BIG: ReadonlySet<SfxEvent> = new Set(['tierHit', 'winStinger', 'loseStinger'])

const MAX_CONCURRENT = 8
const DUCK_MS = 300
const DUCK_FACTOR = 0.4

// The asset base: Vite's `base` (the app is served under /sch.dev/ on
// GitHub Pages — a root-absolute '/resource/sfx' 404s there, so the path
// must be base-relative; in dev/test BASE_URL is '/').
const BASE = `${import.meta.env.BASE_URL}resource/sfx`

let ready = false
/** Events whose asset failed to load (silenced, never retried). */
const missing = new Set<SfxEvent>()
/** Voices currently playing (the concurrency cap). */
let active = 0
/** A big event ducked the small ones until this timestamp. */
let duckUntil = 0

function load(): void {
  if (ready) return
  ready = true
  for (const event of Object.keys(VOLUME) as SfxEvent[]) {
    new Howl({
      src: [`${BASE}/${event}.wav`],
      volume: VOLUME[event],
      onloaderror: () => missing.add(event),
      onplayerror: () => missing.add(event),
    })
  }
}

/** Play one sound-map event (UX §10). No-op for a missing asset or when
 *  the concurrency cap is reached. `rate` varies the pitch (±5% for
 *  toss/land, rising for chip ticks, tier-rank for the tier hit). */
export function playSfx(event: SfxEvent, opts: { rate?: number } = {}): void {
  load()
  if (missing.has(event)) return
  if (active >= MAX_CONCURRENT) return
  const now = performance.now()
  const big = BIG.has(event)
  if (big) duckUntil = now + DUCK_MS
  const ducked = !big && now < duckUntil
  const volume = VOLUME[event] * (ducked ? DUCK_FACTOR : 1)
  const rate = opts.rate ?? 1
  const howl = new Howl({
    src: [`${BASE}/${event}.wav`],
    volume,
    rate,
    onplay: () => {
      active++
    },
    onend: () => {
      active--
    },
    onplayerror: () => {
      active--
      missing.add(event)
    },
  })
  howl.play()
}

/** The base volume of an event (for tests / tuning). */
export function sfxVolume(event: SfxEvent): number {
  return VOLUME[event]
}
